apiVersion: v1
kind: Pod
metadata:
  name:      anthosresourcelimit
spec:
  containers:
    - name:  pause
      image: k8s.gcr.io/pause
      resources:
      requests:
        memory: "1Gi"
        cpu: "1"
