kind: PersistentVolume
apiVersion: v1
metadata:
  name: mysql-pv
  labels:
    name: mysql-pv-1-0-0
spec:
  capacity:
    storage: 2Gi
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  gcePersistentDisk:
    pdName: models-1-0-0
    fsType: ext4
    readOnly: true
